[DATABASE]
REDIS_URL = "redis://:passwd@localhost:6379/10"
PGSQL_URL = "postgresql://account:passwd@localhost:3306/database"
MYSQL_URL = "mysql+mysqlconnector://account:passwd@localhost:3306/database"
